# Generated by Django 2.2.7 on 2019-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_scolarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ch', models.CharField(max_length=8)),
                ('nom_ch', models.CharField(max_length=15)),
                ('prenom_ch', models.CharField(max_length=15)),
                ('photo_ch', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ens', models.CharField(max_length=8)),
                ('nom_ens', models.CharField(max_length=16)),
                ('prenom_ens', models.CharField(max_length=15)),
                ('niv', models.CharField(max_length=3)),
                ('groupe', models.IntegerField()),
                ('code_module', models.CharField(max_length=8)),
                ('photo_ens', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('sect', models.CharField(max_length=5)),
                ('groupe', models.IntegerField()),
                ('photo_et', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_mod', models.CharField(max_length=8)),
                ('niv', models.CharField(max_length=3)),
                ('sem', models.IntegerField()),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=8)),
                ('code_mod', models.CharField(max_length=8)),
                ('ci', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('cf', models.IntegerField()),
            ],
        ),
    ]
