# Generated by Django 2.2.7 on 2019-12-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='label',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant'), ('Charge de scolarite', 'Charge de scolarite')], max_length=30),
        ),
    ]
